/*
* Braze Web SDK v3.3.0
* (c) Braze, Inc. 2021 - http://braze.com
* License available at https://github.com/Appboy/appboy-web-sdk/blob/master/LICENSE
* Compiled on 2021-04-16
*/
'use strict';const h={K:function(a){var b="=".repeat((4-a.length%4)%4);a=(a+b).replace(/\-/g,"+").replace(/_/g,"/");a=atob(a);b=new Uint8Array(a.length);for(let c=0;c<a.length;++c)b[c]=a.charCodeAt(c);return b}};const l={I:()=>{const a=b=>{const c=(Math.random().toString(16)+"000000000").substr(2,8);return b?"-"+c.substr(0,4)+"-"+c.substr(4,4):c};return a()+a(!0)+a(!0)+a()}};function q(a){if("indexedDB"in a.C)return a.C.indexedDB}function r(a){try{if(null==q(a))return!1;q(a).open("Braze IndexedDB Support Test");if("undefined"!==typeof window){const b=window.ka||window.ja||window.ma;if(b&&b.J&&b.J.id)return a.f.info("Not using IndexedDB for storage because we are running inside an extension"),!1}return!0}catch(b){return a.f.info("Not using IndexedDB for storage due to following error: "+b),!1}}
function t(a,b,c){const f=q(a).open(a.b.g,a.b.VERSION);if(null==f)return"function"===typeof c&&c(),!1;f.onupgradeneeded=e=>{a.f.info("Upgrading indexedDB "+a.b.g+" to v"+a.b.VERSION+"...");e=e.target.result;for(const d in a.b.c)a.b.c.hasOwnProperty(d)&&!e.objectStoreNames.contains(a.b.c[d])&&e.createObjectStore(a.b.c[d])};f.onsuccess=e=>{const d=e.target.result;d.onversionchange=()=>{d.close();"function"===typeof c&&c();a.f.error("Needed to close the database unexpectedly because of an upgrade in another tab")};
b(d)};f.onerror=e=>{a.f.info("Could not open indexedDB "+a.b.g+" v"+a.b.VERSION+": "+e.target.errorCode);"function"===typeof c&&c();return!0};return!0}
function v(a,b,c,f){r(a)?t(a,e=>{e.objectStoreNames.contains(b)?(e=e.transaction([b],"readonly").objectStore(b).openCursor(null,"prev"),e.onerror=()=>{a.f.error("Could not open cursor for "+b+" on indexedDB "+a.b.g);"function"===typeof f&&f()},e.onsuccess=d=>{d=d.target.result;null!=d&&null!=d.value&&null!=d.key?c(d.key,d.value):"function"===typeof f&&f()}):(a.f.error("Could not retrieve last record from "+b+" on indexedDB "+a.b.g+" - "+b+" is not a valid objectStore"),"function"===typeof f&&f())},
f):"function"===typeof f&&f()}
class w{constructor(a,b){this.C="undefined"===typeof window?self:window;this.b=a;this.f=b}setItem(a,b,c,f,e){if(!r(this))return"function"===typeof e&&e(),!1;const d=this;return t(this,g=>{g.objectStoreNames.contains(a)?(g=g.transaction([a],"readwrite").objectStore(a).put(c,b),g.onerror=()=>{d.f.error("Could not store object "+b+" in "+a+" on indexedDB "+d.b.g);"function"===typeof e&&e()},g.onsuccess=()=>{"function"===typeof f&&f()}):(d.f.error("Could not store object "+b+" in "+a+" on indexedDB "+
d.b.g+" - "+a+" is not a valid objectStore"),"function"===typeof e&&e())},e)}getItem(a,b,c){if(!r(this))return!1;const f=this;return t(this,e=>{e.objectStoreNames.contains(a)?(e=e.transaction([a],"readonly").objectStore(a).get(b),e.onerror=()=>{f.f.error("Could not retrieve object "+b+" in "+a+" on indexedDB "+f.b.g)},e.onsuccess=d=>{d=d.target.result;null!=d&&c(d)}):f.f.error("Could not retrieve object "+b+" in "+a+" on indexedDB "+f.b.g+" - "+a+" is not a valid objectStore")})}clearData(){if(!r(this))return!1;
const a=[];for(const c in this.b.c)this.b.c.hasOwnProperty(c)&&this.b.c[c]!==this.b.c.v&&a.push(this.b.c[c]);const b=this;return t(this,function(c){c=c.transaction(a,"readwrite");for(let f=0;f<a.length;f++)c.objectStore(a[f]).clear().onerror=function(){b.f.error("Could not clear "+this.source.name+" on indexedDB "+b.b.g)};c.onerror=function(){b.f.error("Could not clear object stores on indexedDB "+b.b.g)}})}};const x={s:function(a){if(void 0!==a||void 0===x.j)x.j=!!a;x.B||(x.B=!0)},la:function(){x.B=!1;x.j=void 0;x.f=void 0},na:function(a){"function"!==typeof a?x.info("Ignoring setLogger call since logger is not a function"):(x.s(),x.f=a)},oa:function(){x.s();x.j?(console.log("Disabling Appboy logging"),x.j=!1):(console.log("Enabled Appboy logging"),x.j=!0)},info:function(a){x.j&&(a="Appboy: "+a,null!=x.f?x.f(a):console.log(a))},warn:function(a){x.j&&(a="Appboy SDK Warning: "+a+" (v3.3.0)",null!=
x.f?x.f(a):console.warn(a))},error:function(a){x.j&&(a="Appboy SDK Error: "+a+" (v3.3.0)",null!=x.f?x.f(a):console.error(a))}};var y={CustomEvent:"ce",ba:"p",H:"pc",G:"ca",da:"i",ca:"ie",R:"cci",S:"ccic",O:"ccc",P:"ccd",ia:"ss",ha:"se",aa:"si",Z:"sc",Y:"sbc",$:"sfe",T:"iec",ga:"lr",L:"uae",N:"ci",M:"cc",ea:"lcaa",fa:"lcar",V:"inc",U:"add",W:"rem",X:"set"},z=w,A={h:{g:"AppboyServiceWorkerAsyncStorage",VERSION:5,c:{l:"data",F:"pushClicks",A:"pushSubscribed",o:"fallbackDevice",D:"cardUpdates",v:"optOut"},m:1}},B=x;function C(){return new Promise(function(a,b){const c=A.h;v(new z(c,B),c.c.v,b,a)})};function D(a,b,c){return new Promise(function(f,e){const d={};d.time=Math.floor((new Date).valueOf()/1E3);d.device_id=c;d.api_key=a;d.sdk_version="3.3.0";d.sdk_flavor="amp";d.respond_with={config:{config_time:0}};fetch(b+"/data/",{method:"POST",headers:{"Content-type":"application/json","X-Braze-Api-Key":a},body:JSON.stringify(d)}).then(function(g){g.ok||B.error("Unable to get config: "+g.status);return g.json()}).then(function(g){g.error?(B.error("Unable to get config: "+g.error),e()):
(g={userVisibleOnly:!0,applicationServerKey:h.K(g.config.vapid_public_key)},f(g))}).catch(function(g){B.error("Unable to get config: "+g);e()})})}
function H(a,b,c,f,e,d,g,k){return new Promise(function(m,n){const p={};p.device_id=c;p.api_key=a;p.sdk_version="3.3.0";null!=d&&(p.sdk_flavor=d);let E=null,F=null,G=null;e&&(G=e.endpoint,e.getKey&&(E=btoa(String.fromCharCode.apply(null,new Uint8Array(e.getKey("p256dh")))),F=btoa(String.fromCharCode.apply(null,new Uint8Array(e.getKey("auth"))))));p.time=Math.floor((new Date).valueOf()/1E3);p.attributes=[{user_id:f,push_token:G,custom_push_public_key:E,custom_push_user_auth:F}];fetch(b+"/data/",
{method:"POST",headers:{"Content-type":"application/json","X-Braze-Api-Key":p.api_key},body:JSON.stringify(p)}).then(function(u){u.ok||B.error(k+" "+u.status);return u.json()}).then(function(u){u.error?(B.error(k+" "+u.error),n()):(B.info(g),m())}).catch(function(u){B.error(k+" "+u);n()})})}
function I(a,b){return C().then(function(){const c=A.h;v(new z(c,B),c.c.l,function(f,e){f=Math.floor((new Date).valueOf()/1E3);const d=e.data;d.time=f;a.time=f;a.user_id=e.userId;d.events=[a];d.sdk_version="3.3.0";fetch(e.baseUrl+"/data/",{method:"POST",headers:{"Content-type":"application/json","X-Braze-Api-Key":d.api_key},body:JSON.stringify(d)}).then(function(g){g.ok||B.error("Unable to log "+b+": "+g.status);return g.json()}).then(function(g){g.error?B.error("Unable to log "+b+":",g.error):
B.info("Successfully logged "+b);return Promise.resolve()}).catch(function(g){B.error("Unable to log "+b+":",g);return Promise.resolve()})})}).catch(function(){return Promise.reject("Not sending data to Braze backend due to opt-out.")})};function J(){const a=self.location.search.match(/apiKey=([^&]+)/i);if(a)return a[1];B.error("Missing API key in query params.");return null}function K(){const a=self.location.search.match(/baseUrl=([^&]+)/i);if(a)return a[1];B.error("Missing base URL in query params.");return null};function L(a,b){self.clients.matchAll().then(function(c){for(let f=0;f<c.length;f++)c[f].postMessage({command:a,payload:b})})}
function M(a,b,c,f){return D(a,b,c).then(function(e){return self.registration.pushManager.subscribe(e)}).then(function(e){L("amp-web-push-subscribe",null);return H(a,b,c,f,e,"amp","Successfully sent AMP push subscription to Braze backend.","Unable to send AMP push subscription to Braze backend.")}).catch(function(){B.error("Failed to subscribe for AMP push.");return Promise.reject()})}
function N(){self.registration.pushManager.getSubscription().then(function(a){return a?self.registration.pushManager.permissionState(a.options):null}).then(function(a){L("amp-web-push-subscription-state","granted"===a)})}
function O(){const a=A.h,b=new z(a,B);return(new Promise(function(c,f){v(b,a.c.l,function(e,d){M(d.data.api_key,d.baseUrl,d.data.device_id,d.userId).then(function(){c()}).catch(function(){f()})},function(){const e=J(),d=K();v(b,a.c.o,function(g,k){M(e,d,k,null).then(function(){c()}).catch(function(){f()})},function(){const g=l.I();(new Promise(function(k,m){b.setItem(a.c.o,a.m,g,k,m)})).then(function(){return M(e,d,g,null)}).then(function(){c()}).catch(function(){f()})})})})).then(function(){return new Promise(function(c,
f){b.setItem(a.c.A,a.m,!0,c,f)})})}
function P(){return self.registration.pushManager.getSubscription().then(function(a){return a.unsubscribe()}).then(function(){L("amp-web-push-unsubscribe",null);const a=A.h,b=new z(a,B);return(new Promise(function(c,f){v(b,a.c.l,function(e,d){H(d.data.api_key,d.baseUrl,d.data.device_id,d.userId,null,"amp","Successfully sent AMP push unsubscription to Braze backend.","Unable to send AMP push unsubscription to Braze backend.").then(function(){c()}).catch(function(){f()})},function(){v(b,a.c.o,function(e,
d){e=J();const g=K();H(e,g,d,null,null,"amp","Successfully sent AMP push unsubscription to Braze backend.","Unable to send AMP push unsubscription to Braze backend.").then(function(){c()}).catch(function(){f()})},function(){B.error("No device found during unsubscription.");f()})})})).then(function(){return new Promise(function(c,f){b.setItem(a.c.A,a.m,!1,c,f)})})}).catch(function(){B.error("Failed to unsubscribe for AMP push.");return Promise.reject()})};function Q(a,b){a.waitUntil(b.catch(function(c){c&&B.info(c)}))};B.s(!0);
function R(a){if(null==a||0===Object.keys(a).length)return Promise.reject("Server has no pending push message for this registration. Ignoring push event.");const b=a.t,c=a.a,f=a.i,e=a.img,d={url:a.u,ab_ids:{cid:a.cid},extra:a.e},g=a.ri;a.ab_push_fetch_test_triggers_key&&(B.info("Service worker 3.3.0 found trigger fetch key in push payload."),d.fetchTriggers=!0);var k=a.ab_cd;if(null!=k){var m=A.h;(new z(m,B)).setItem(m.c.D,(new Date).valueOf(),{userId:a.ab_cd_uid,card:k})}a=a.pab||[];k=
{};for(m=0;m<a.length;m++)if(null!=a[m]&&null!=a[m].action){let n;switch(a[m].a){case "ab_none":n=null;break;case "ab_uri":if(n=a[m].u,null==n||""===n)n="/"}k[a[m].action]=n}d.actionTargets=k;B.info("Displaying push notification!");return self.registration.showNotification(b,{body:c,icon:f,image:e,data:d,actions:a,requireInteraction:g}).catch(function(n){B.info(n)})}self.addEventListener("install",function(a){a.waitUntil(self.skipWaiting())});self.addEventListener("activate",function(){return self.clients.claim()});
self.addEventListener("push",function(a){B.info("Service worker 3.3.0 received push");null!=a.data&&null!=a.data.json?Q(a,R(a.data.json())):Q(a,new Promise(function(b,c){const f=A.h;v(new z(f,B),f.c.l,function(e,d){const g=d.data;C().then(function(){return fetch(d.baseUrl+"/web_push/",{method:"POST",headers:{"Content-type":"application/json","X-Braze-Api-Key":g.api_key},body:JSON.stringify(g)})}).then(function(k){return k.ok?k.json():(B.error("Unable to retrieve push payload from server: "+
k.status),Promise.reject())}).then(function(k){B.info("Retrieved push payload from server");b(R(k))}).catch(function(k){c("Unable to retrieve push payload from server or user has opt-out: "+k)})})}))});
self.addEventListener("notificationclick",function(a){if(a&&a.notification&&(a.notification.close(),null!=Notification&&Notification.prototype.hasOwnProperty("data")&&a.notification.data&&a.notification.data.ab_ids)){var b=null!=a.action&&""!==a.action;var c=b?I({name:y.G,data:{cid:a.notification.data.ab_ids.cid,a:a.action}},"push button click"):I({name:y.H,data:{cid:a.notification.data.ab_ids.cid}},"push click");if(!b){const g={lastClick:(new Date).valueOf(),trackingString:a.notification.data.ab_ids.cid};
a.notification.data.fetchTriggers&&(g.fetchTriggers=!0);const k=A.h,m=new z(k,B);var f=c.then(function(){return new Promise(function(n,p){m.setItem(k.c.F,k.m,g,n,p)})}).catch(function(){B.info("Not storing push click due to no click event being created.");return Promise.resolve()})}if(b)var e=a.notification.data.actionTargets[a.action];else if(e=a.notification.data.url,null==e||""===e)e="/";var d;null!=e&&""!==e&&(d=clients.matchAll({type:"window"}).then(function(){if(clients.openWindow)return clients.openWindow(e)}));
Q(a,Promise.all([d,f]))}});self.addEventListener("pushsubscriptionchange",function(a){Q(a,C().then(function(){let b={userVisibleOnly:!0};null!=a.oldSubscription&&(b=a.oldSubscription.options);return self.registration.pushManager.subscribe(b)}).then(function(b){const c=A.h;return new Promise(function(f,e){v(new z(c,B),c.c.l,function(d,g){H(g.data.api_key,g.baseUrl,g.data.device_id,g.userId,b,null,"Successfully resubscribed user after expiration","Unable to resubscribe user").then(function(){f()}).catch(function(){e()})})})}).catch(function(){return Promise.reject("Not resubscribing user for push due to opt-out.")}))});
self.addEventListener("message",function(a){a.waitUntil&&a.data.command&&a.waitUntil(C().then(function(){switch(a.data.command){case "amp-web-push-subscription-state":return N(),Promise.resolve();case "amp-web-push-subscribe":return O();case "amp-web-push-unsubscribe":return P();default:return Promise.resolve()}}).catch(function(){B.info("Ignoring message from amp-web-push due to opt-out.");return Promise.resolve()}))});
